[package]
name = "dreamsmith"
version = "0.1.0"
edition = "2024"

[dependencies]
a1800_codec = "1.0.0"
anyhow = "1.0.100"
binrw = "0.15.0"
hex = "0.4.3"
eframe = "0.31"
int-enum = "1.2.0"
rodio = { version = "0.21", default-features = false, features = ["playback", "hound"] }
hound = "3"
pico-args = "0.5.0"
sha2 = "0.10.9"
